import numpy as np
import pandas as pd
import streamlit as st
import altair as alt


def guess():

    # Set the initial value of the slide bar
    slider_value = 0

    # Set the range of the slide bar
    slider_range = (1, 50)

    # Generate a random number to be guessed
    target_number = 12
    # Set the initial value of the start button
    start_button_clicked = False
    # Set the initial value of the guess value
    guess_value = None

    # Create the slide bar
    slider = st.slider("Given that you know that the United States has 4% of the world's population, please guess the percentage of the planet's MSW generated by the United States.", *slider_range, value=slider_value, format = "%d%%")

    # Create the start button
    start_button = st.button("Start")

    if start_button:
        start_button_clicked = True
        guess_value = slider

    if start_button_clicked and guess_value == target_number:
        st.success("Congratulations! You guessed the correct number.")
    elif start_button_clicked and guess_value != target_number:
        st.error('Sorry, the truth answer is 12%.')


def set_Intro():

    st.header("Introduction")
    with st.container():
        st.subheader("What is waste?")
        # font-weight:bold;
        # st.write('<span style="background-color:#C5DFB4;font-size:28px">What is waste ?</span>', unsafe_allow_html=True)
        col1, col2, col3 = st.columns([0.45,0.05,0.5])
        col3.markdown(" ")
        col3.markdown(''' Waste is any substance which is discarded after primary use, 
                    or is worthless, defective and of no use. 
                    From the definition of EPA, waste can be divided into hazardous waste and non-hazardous. 
                    Hazardous waste includes radioactive waste, industrial waste, electronic waste and medical waste. 
                    Non-hazardous waste is also called solid waste, the largest part of solid waste is municipal solid waste.

            ''')
        col1.image("src/Waste_Type.png")
    # col1, col2, col3 = st.columns([0.7, 4.1, 0.7])
    # col2.image("src/Waste_Type.png", use_column_width=True)

    st.markdown(" ")
    st.markdown(" ")
    st.markdown(" ")

    st.markdown("#### Take a guess 🤔")

    guess()

    with st.expander("See details 🧑‍🏫 "):
        st.write('''Every year, the globe creates <span style="color:red">2.01</span> billion tons of municipal solid garbage, with at least <span style="color:red">33%</span> of that not being managed in an environmentally sustainable manner. 
                    Worldwide, waste generated per person per day averages 0.74 kilogram but ranges widely, from 0.11 to 4.54 kilograms.''', unsafe_allow_html=True)
        # st.markdown('''Every year, the globe creates **2.01** billion tons of municipal solid garbage, with at least **33%** of that not being managed in an environmentally sustainable manner. 
        #             Worldwide, waste generated per person per day averages 0.74 kilogram but ranges widely, from 0.11 to 4.54 kilograms. 
        # ''')
        st.write('''Despite having only 4% of the world's population, the United States produces more than <span style="color:red">12%</span> of the world's rubbish. 
    In 2018, the United States wasted more than 292 million tons of municipal solid waste (MSW), which includes materials abandoned by residences, companies, and institutions such as universities and libraries. 
    The majority of waste (<span style="color:red">62%</span>) discarded by homes and companies in the United States is eventually dumped in landfills or burned in incinerators.
        ''', unsafe_allow_html=True)

    st.markdown(" ")
    st.markdown(" ")
    st.markdown(" ")
    st.subheader("What is waste management?")
    st.markdown('''Waste can be recycled if it is collected and managed properly. Waste materials such as plastic, glass, and paper can be separated into different columns and processed to create new goods, saving natural resources. Furthermore, when this trash is not recycled, it frequently ends up in landfills or oceans, endangering human health and marine life. In most parts of the world, sewage treatment is inadequate, resulting in eutrophication and beach closures. Each year, an estimated 8 million tons of plastic wind up in the oceans, according to the World Wildlife Fund (WWF).
    ''')
    st.markdown('''Waste management encompasses the process of managing waste from its inception to its final disposal. 
                First, the waste is generated from industrial and human activities, then concentrated in the collection area, of which recyclable waste will be sent to the recycling depository by car, 
                and then through the recycling facility for recycling; 
                non-recyclable part by truck to the transfer station, part can be taken to compost,
                part of the recycling, part of the burning, burning the remaining ash and the rest of the unmanageable finally to landfill.
    ''')

    col1, col2, col3 = st.columns([0.5, 4.5, 0.5])
    col2.image('src/cycle.png')
